apiVersion: v1
kind: Pod
metadata:
  name: name
spec:
  containers:
    - name: c1
      image: nginx
      ports:
        - containerPort: 80

#kubectl create -f pod.yaml  -----it create a pod with requirements
#kubectl get po ------------------it list the pods
