apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: swiggy
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: instance
                operator: In
                values:
                  - logs
  containers:
    - name: c1
      image: httpd
      ports:
        - containerPort: 80
