apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: mysecretname
  annotations:
    kubernetes.io/service-account.name: jenkins


#kubectl apply -f secret-token.yaml -n webapps
#kubectl describe secret mysecretname -n weapps
